---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    firewalld_custom_services:
      - name: ourSSH1
        description: ourSSH1
        port: 8123
        proto: tcp
      - name: ourSSH2
        description: ourSSH2
        port: 8124
        proto: tcp
    firewalld_allowed_services:
      - ourSSH1
      - ourSSH2
  roles:
    - role: jj0cker.firewalld
