---
name: CI
'on':
  push:
  pull_request:
    branches:
      - main
      - dev
jobs:
  test:
    name: Molecule tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase.
        uses: actions/checkout@v2

      - name: Setup Python 3.
        uses: actions/setup-python@v2
